# coding: utf-8

"""
    DCS (Gitea) API.

    This documentation describes the DCS (Gitea) API.  # noqa: E501

    OpenAPI spec version: 1.16.3+dcs
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dcs_api_client
from dcs_api_client.models.general_repo_settings import GeneralRepoSettings  # noqa: E501
from dcs_api_client.rest import ApiException


class TestGeneralRepoSettings(unittest.TestCase):
    """GeneralRepoSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeneralRepoSettings(self):
        """Test GeneralRepoSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dcs_api_client.models.general_repo_settings.GeneralRepoSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
