# coding: utf-8

"""
    DCS (Gitea) API.

    This documentation describes the DCS (Gitea) API.  # noqa: E501

    OpenAPI spec version: 1.20.3+dcs
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dcs_api_client
from dcs_api_client.models.change_files_options import ChangeFilesOptions  # noqa: E501
from dcs_api_client.rest import ApiException


class TestChangeFilesOptions(unittest.TestCase):
    """ChangeFilesOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChangeFilesOptions(self):
        """Test ChangeFilesOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dcs_api_client.models.change_files_options.ChangeFilesOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
