# coding: utf-8

"""
    DCS (Gitea) API.

    This documentation describes the DCS (Gitea) API.  # noqa: E501

    OpenAPI spec version: 1.16.3+dcs
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dcs_api_client
from dcs_api_client.models.combined_status import CombinedStatus  # noqa: E501
from dcs_api_client.rest import ApiException


class TestCombinedStatus(unittest.TestCase):
    """CombinedStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCombinedStatus(self):
        """Test CombinedStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dcs_api_client.models.combined_status.CombinedStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
