# coding: utf-8

"""
    DCS (Gitea) API.

    This documentation describes the DCS (Gitea) API.  # noqa: E501

    OpenAPI spec version: 1.20.3+dcs
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dcs_api_client
from dcs_api_client.api.catalog_api import CatalogApi  # noqa: E501
from dcs_api_client.rest import ApiException


class TestCatalogApi(unittest.TestCase):
    """CatalogApi unit test stubs"""

    def setUp(self):
        self.api = dcs_api_client.api.catalog_api.CatalogApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_catalog_get_entry(self):
        """Test case for catalog_get_entry

        Catalog entry  # noqa: E501
        """
        pass

    def test_catalog_get_metadata(self):
        """Test case for catalog_get_metadata

        Catalog entry metadata (manifest.yaml in JSON format)  # noqa: E501
        """
        pass

    def test_catalog_list_languages(self):
        """Test case for catalog_list_languages

        Catalog list owners  # noqa: E501
        """
        pass

    def test_catalog_list_subjects(self):
        """Test case for catalog_list_subjects

        Catalog list subjects  # noqa: E501
        """
        pass

    def test_catalog_search(self):
        """Test case for catalog_search

        Catalog search  # noqa: E501
        """
        pass

    def test_catalog_search_owner(self):
        """Test case for catalog_search_owner

        Catalog search by owner  # noqa: E501
        """
        pass

    def test_catalog_search_repo(self):
        """Test case for catalog_search_repo

        Catalog search by repo  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
