# coding: utf-8

"""
    DCS (Gitea) API.

    This documentation describes the DCS (Gitea) API.  # noqa: E501

    OpenAPI spec version: 1.20.3+dcs
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dcs_api_client
from dcs_api_client.models.new_issue_pins_allowed import NewIssuePinsAllowed  # noqa: E501
from dcs_api_client.rest import ApiException


class TestNewIssuePinsAllowed(unittest.TestCase):
    """NewIssuePinsAllowed unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNewIssuePinsAllowed(self):
        """Test NewIssuePinsAllowed"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dcs_api_client.models.new_issue_pins_allowed.NewIssuePinsAllowed()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
