# coding: utf-8

"""
    DCS (Gitea) API.

    This documentation describes the DCS (Gitea) API.  # noqa: E501

    OpenAPI spec version: 1.20.3+dcs
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dcs_api_client
from dcs_api_client.models.label_template import LabelTemplate  # noqa: E501
from dcs_api_client.rest import ApiException


class TestLabelTemplate(unittest.TestCase):
    """LabelTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLabelTemplate(self):
        """Test LabelTemplate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dcs_api_client.models.label_template.LabelTemplate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
